version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "orders-websocket-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6ge24nirg7k8"
s3_prefix = "orders-websocket-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = [
    "OnConnectFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/orders-websocket-api-onconnect-function",
    "OnDisconnectFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/orders-websocket-api-ondisconnect-function",
    "OnSubscribeFunction=084882962555.dkr.ecr.us-west-2.amazonaws.com/orders-websocket-api-onsubscribe-function"
]
